### ISSUE TITLE
Navigation misbehavior on AVS details view

### ISSUE THREAD

**Issue by Zishan-7** [NethermindEth/restaking-dashboard#137]
When you go to AVS details operator tab and then try to go back to the previous page, it does not work. it just gets stuck there.
 
 

https://github.com/user-attachments/assets/9ce0ebcd-98c9-41db-9c19-6d308a916c52

**Comment by rubo** [comment]
The problem is that switching to the Operators tab alters the URL, adding query parameters. However, the query parameters aren't specific enough to open the Operators tab on reload. We either need to develop a better solution for each tab or not alter the URL on the tab change. I prefer to go with the latter to avoid delays. Later, we may reconsider the approach.
